### ISSUE TITLE
Regex with laravel-hyrule

### ISSUE THREAD

**Issue by RenatoKW** [square/laravel-hyrule#1]
Is there a way to use regular expressions with this API? Haven't see any mentions in the documentation for this. 
Ty

**Comment by bezhermoso** [comment]
Any and all built-in rules in Laravel is possible :) Just use the rule name as if it's a method in the builder, and it will be appended as a rule. For example, you can use `regex` like so:

```php
$builder = Hyrule::create()
    ->string('slug')
       ->regex('/^[a-z0-9\-]$/')
       ->end()
    // etc.
```

**Comment by RenatoKW** [comment]
Very Nice!! Thanks for the quick reply!!
