### ISSUE TITLE
Please add  file uploads support to the latest 1x release version

### ISSUE THREAD

**Issue by thegruffaloop** [square/laravel-hyrule#15]
**The latest 1x version doesn't have support for the file uploads** (missing https://github.com/square/laravel-hyrule/blob/1.x/src/Nodes/FileNode.php)

Latest 1x version was released on **July 1 2022**
FileNode support was added to 1x branch few days later on **July 8 2022** https://github.com/square/laravel-hyrule/commit/bacb8a416b81d9f9255f87cc53b3b070d80e7ff2 

**But there were no any new releases for 1x version from that time**. As a result when I install package via
`composer require square/laravel-hyrule:^1.0` I don't get support for file uploads.

**BTW**: the latest 1x version seems to be 1.3.0 while 1.2.2 is documented as latest https://github.com/square/laravel-hyrule/releases

Thank you

**Comment by bezhermoso** [comment]
Hi @ElvirBekirov, thanks for bringing this to our attention. I've cut a `1.4.0` release that should bring support for file uploads: https://github.com/square/laravel-hyrule/releases/tag/1.4.0
