### ISSUE TITLE
illuminate/validation ^9.0

### ISSUE THREAD

**Issue by bohemima** [square/laravel-hyrule#3]
Any reason this would not work with 9.0, or a reason for it to stay on 8?

Will look closer into it over the weekend if I get some time!

**Comment by bezhermoso** [comment]
I'm not aware of any change to Validation APIs between `8.x...9.x` that makes this incompatible, I just haven't vetted it yet.

It should be fairly quick to check by upgrading the version used in tests: https://github.com/square/laravel-hyrule/blob/master/composer.json#L15

**Comment by bohemima** [comment]
Good stuff, will give it a test go over the weekend!

**Comment by bezhermoso** [comment]
Hi @bohemima, did you get the chance testing it over the weekend? Tests are passing against `^9.0` so I'm inclined to merge it in real soon.

**Comment by bohemima** [comment]
Did only a few quick test, nothing advanced but it worked great! @bezhermoso

**Comment by bezhermoso** [comment]
@bohemima I appreciate the help! I will cut a release sometime today.

**Comment by bezhermoso** [comment]
https://github.com/square/laravel-hyrule/releases/tag/2.2.0 has been cut to enable Laravel 9.x support.
