### ISSUE TITLE
using ->end() doesn't give RootNode's typehint to the IDE

### ISSUE THREAD

**Issue by sawirricardo** [square/laravel-hyrule#6]
since `->end()` return the CompoundNode, instead of RootNode, it didn't give access to method like ->string(), ->numeric etc

Maybe we can use something like public function end(): CompoundNode|RootNode so we can have access to that method.

Thoughts?

**Comment by bezhermoso** [comment]
Hi @sawirricardo,

This should be taken care of via these [`@mixin` PHPDoc directives on `CompoundNode`.](https://github.com/square/laravel-hyrule/blob/7c76a65d703825545415fe8af6af97a67a9334de/src/Nodes/CompoundNode.php#L5-L8)

What IDE are you using? If you can get it to understand those, you should get them in auto-complete. Here is what it looks like in IntelliJ IDEA or PHPStorm:

<img width="611" alt="Screen Shot 2022-06-14 at 10 23 58 AM" src="https://user-images.githubusercontent.com/1437428/173640611-10a1ba76-d908-4e63-b1bb-5a1383a69d27.png">

**Comment by sawirricardo** [comment]
Using vscode with [laravel-ide-helper](https://github.com/barryvdh/laravel-ide-helper). maybe due to the ide-helper package? it seems vscode doesnt take the things 
<img width="820" alt="image" src="https://user-images.githubusercontent.com/37329575/173709202-1a85aa12-62d9-4805-be52-7a3028ad13e8.png">

**Comment by bezhermoso** [comment]
I did some quick Googling and found this: https://github.com/neild3r/vscode-php-docblocker/issues/120.

I'm going to close this as I don't believe it's a Hyrule issue. Let me know if that VSCode plugin helps!

**Comment by sawirricardo** [comment]
@bezhermoso  Oops, Actually, I've installed the docblocker ext too, but it's not working. Is it possible to simply add the return docblock to include `RootNode`? like this 
<img width="605" alt="image" src="https://user-images.githubusercontent.com/37329575/173731030-fe3a39e4-1deb-4538-ac36-193e6ac912ec.png">
that way the IDE (vscode) works

**Comment by bezhermoso** [comment]
Hi @sawirricardo, VSCode auto-complete should work better now: https://github.com/square/laravel-hyrule/pull/1

<img width="537" alt="Screen Shot 2022-07-09 at 10 03 27 AM" src="https://user-images.githubusercontent.com/1437428/178115756-419d4e64-9fa7-41c8-8906-861c160a41eb.png">
