### ISSUE TITLE
No support for file nodes

### ISSUE THREAD

**Issue by dziurka** [square/laravel-hyrule#7]
Hi!

Today I noticed that there is no way to add validation for files.
Perhaps some more universal Node class could be used as a fallback for unforeseen types?

**Comment by bezhermoso** [comment]
Hi @dziurka, thanks for the feedback. It is indeed missing support for files, and I'm working on it now: https://github.com/square/laravel-hyrule/pull/8

As for a more universal node type: although that would be convenient, I feel it would go against the goal of ensuring a level of strictness to rule-sets built via Hyrule. Right now that's achieved with the limited set of type-specific property methods.

**Comment by bezhermoso** [comment]
Support added, I will cut a release next week.
